spring:
  r2dbc:
    username: ${NOTION_S3_DATABASE_USERNAME:postgres}
    password: ${NOTION_S3_DATABASE_PASSWORD:postgres}
    url: ${NOTION_S3_DATABASE_URL:r2dbc:postgresql://localhost:5432/notion-s3}
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:200MB}
      max-request-size: ${MAX_REQUEST_SIZE:200MB}

  flyway:
    enabled: true
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_URL:http://localhost:8761/eureka}

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}
  bucket: ${MINIO_BUCKET:my-bucket}

server:
  port: 0

logging:
  level:
    org:
      springframework:
        security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        sliding-window-type: count_based
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s