server:
  port: 8765

app:
  security-server-name: notion-security

spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_URL:http://localhost:8761/eureka}

logging:
  level:
    root: ${GATEWAY_LOG_LEVEL:DEBUG}

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        sliding-window-type: count_based
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s