server:
  port: 8765

app:
  security-server-name: notion-security

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: notion-core
          uri: lb://notion
          predicates:
            - Path=/notion-core/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_URL:http://localhost:8761/eureka}

logging:
  level:
    root: ${GATEWAY_LOG_LEVEL:DEBUG}

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        sliding-window-type: count_based
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /notion/v3/api-docs
        name: Notion Service
      - url: /notion-s3/v3/api-docs
        name: S3 Service
      - url: /notion-security/v3/api-docs
        name: Security Service