application:
  security:
    jwt:
      expiration: 123456789
      server-expiration: 123456789009876
      secret-key: MegaLargeSigningSecretKeyForDemoApplicationMegaLargeSigningSecretKeyForDemoApplication

spring:
  kafka:
    producer:
      client-id: ${spring.application.name}
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      retries: 3
    bootstrap-servers: host.docker.internal:29092,host.docker.internal:29093, host.docker.internal:29094

  datasource:
    url: ${NOTION_CORE_DATABASE_URL:jdbc:postgresql://localhost:5432/notion-core}
    username: ${NOTION_CORE_DATABASE_USERNAME:postgres}
    password: ${NOTION_CORE_DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true

sse:
  timeout: 3000

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: shutdown

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_URL:http://localhost:8761/eureka}
logging:
  level:
    root: debug

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        sliding-window-type: count_based
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s