application:
  security:
    jwt:
      expiration: 123456789
      server-expiration: 123456789009876
      secret-key: MegaLargeSigningSecretKeyForDemoApplicationMegaLargeSigningSecretKeyForDemoApplication

spring:
  datasource:
    url: ${NOTION_CORE_DATABASE_URL:jdbc:postgresql://localhost:5432/notion-core}
    username: ${NOTION_CORE_DATABASE_USERNAME:postgres}
    password: ${NOTION_CORE_DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true

sse:
  timeout: 3000

server:
  port: 0

feign:
  hystrix:
    enabled: true
  client:
    config:
      executorServiceClient:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: basic

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: shutdown

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    root: debug