spring:
  kafka:
    client-id: ${spring.application.name}
    consumer:
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        auto.offset.reset: latest
        isolation.level: read_committed
        spring.json.trusted.packages: "*"
    bootstrap-servers: kafka1:29092,kafka2:29093,kafka3:29094
  application:
    name: notification

sse:
  timeout: 3000

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_URL:http://localhost:8761/eureka}
